name: mission_diary
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animated_emoji: ^3.1.0
  animations: ^2.0.11
  camerawesome: ^2.0.1
  change_app_package_name: ^1.2.0
  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  device_preview: ^1.2.0
  faker: ^2.1.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.3.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.2
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pull_to_refresh: ^2.0.0
  rive: ^0.13.9
  rxdart: ^0.27.7
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    # - secrets.env

  # fonts:
  # - family: Montserrat
  #   fonts:
  #     - asset: assets/fonts/Montserrat-Thin.ttf
  #       weight: 100
  #     - asset: assets/fonts/Montserrat-ExtraLight.ttf
  #       weight: 200
  #     - asset: assets/fonts/Montserrat-Light.ttf
  #       weight: 300
  #     - asset: assets/fonts/Montserrat-Regular.ttf
  #       weight: 400
  #     - asset: assets/fonts/Montserrat-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/Montserrat-SemiBold.ttf
  #       weight: 600
  #     - asset: assets/fonts/Montserrat-Bold.ttf
  #       weight: 700
  #     - asset: assets/fonts/Montserrat-ExtraBold.ttf
  #       weight: 800
  #     - asset: assets/fonts/Montserrat-Black.ttf
  #       weight: 900
